# [language-server.pylsp.config.pylsp]
# plugins.ruff.enabled = true
# plugins.black.enabled = true

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", outputPath = "$root/$dir/$name" }

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG", "mkd", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "qmd", "workbook"]
soft-wrap.enable = true
roots = [".marksman.toml"]
language-servers = [ "marksman" ]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typst"
scope = "source.typ"
language-servers = ["tinymist"]
injection-regex = "typ"
soft-wrap.enable = true

[[language]]
name = "julia"
scope = "source.jl"
file-types = ["jl"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "runic" }
